### ISSUE TITLE
Unable to drag .thm file onto Marabu

### ISSUE THREAD

**Issue by jakofranko** [hundredrabbits/Marabu#15]
Hey there, just started playing around with this...love it! Wanted to try to drag a new theme onto it and couldn't. 
* I tried it with Left, and also was unable to load a theme
* Dotgrid works perfectly however; I'm able to drag a new theme onto the window and it changes colors without issue
* I installed all three apps through the itch.io client.
* I haven't done anything with any of the files, simply downloaded them through the client
* I'm running Windows 10 

Not sure if you guys are able to test on Windows out there upon the great blue sea, but if not I'd be happy to help debug it myself, just thought I'd mention it here unless anybody else was having the same issue.

Here's a screenshot of Marabu:
![2018-02-14 2](https://user-images.githubusercontent.com/3189302/36241993-bd93a780-11d6-11e8-8473-278cd8506f21.png)

**Comment by neauoire** [comment]
It sounds like you didn't download the themes from Itch.io but from GitHub.
We're migrating the themes format.

Marabu still uses the old themes I think, Dotgrid uses the new ones.
I will push a new update for Marabu and Left that supports the Github version. 

For now, the apps only supports the themes that comes with their associated itch.io bundle.

**Comment by jakofranko** [comment]
That is it precicely. Thanks for the quick reply!

**Comment by neauoire** [comment]
That should be fixed tomorrow :)

**Comment by jakofranko** [comment]
You rock! Thanks so much :)

**Comment by neauoire** [comment]
Marabu is fixed :)

**Comment by jakofranko** [comment]
I just re-installed and am still seeing the same thing 😖 I downloaded the repo locally and initial debugging is showing that the `dragover` and `drop` events aren'r being triggered for some reason...hmm....

**Comment by jakofranko** [comment]
I double checked this on my Mac and there are no issues. Seems to be something Windows related.

**Comment by jakofranko** [comment]
Been looking at this some tonight and am a little baffled. It seems that the `<app id='marabu'>` and `<yu class='wrapper'>` elements that you create in `marabu.js` are blocking any events from happening on `window` behind it (`window.addEventListener('blah', func)` works just fine if I don't insert the main elements).

I had a fluke debugging it where both those elements had 0 height and then I was able to drag stuff onto `window` again.

Really weird, and like I said, only happens on Windows; my Mac works just fine. I'm curious if anybody else is able to replicate this bug? I can't see anything happening on `this.el` or `this.wrapper_el` that would stop bubbling from happening, but I might be missing something?

**Comment by neauoire** [comment]
: ( I have no idea. I could always do a install theme button in the dropdown?

**Comment by neauoire** [comment]
Ah right, Windows doesn't even have the dropdown..

<img width="1019" alt="screen shot 2018-02-17 at 8 43 39 pm" src="https://user-images.githubusercontent.com/1455726/36339129-40f1a12e-1423-11e8-9a41-31975203e726.png">

**Comment by jakofranko** [comment]
Ohhh I forgot there was a menu bar haha, yeah since Windows doesn't have that. I think I've narrowed it down to something to do with `-webkit-app-region: drag;`. Regardless, Dotgrid works fine, so I'm certain there's a solution! Now I'm just figuring out the difference between the two in order to see what's breaking theme dragging for Marabu on Windows but not Dotgrid.

I think this is actually a bug with Electron anyways...if I figure it out I'll submit a PR ;)

**Comment by neauoire** [comment]
Thanks Jako :)

**Comment by jakofranko** [comment]
You got it! I also submitted a bug for electron: https://github.com/electron/electron/issues/11994

definitely an electron thing, not a Marabu thing.

**Comment by neauoire** [comment]
Do you think I could use this on Left as well?
I guess all the apps have the same issue right?

**Comment by jakofranko** [comment]
Yes, I was seeing the same thing on Left, but Dotgrid is already doing this. Donsol maybe too?

**Comment by neauoire** [comment]
Left doesn't even have yu type containers, so ...? I don't understand the fix and I cannot test it :'(

**Comment by jakofranko** [comment]
Ah no worries, I’ll make a PR later this evening for Left then, and I can look at Donsol too. It’s just adding -webkit-app-region: no-drag css property to a largish element that is a child to an element with -webkit-app-region: drag.

**Comment by neauoire** [comment]
Someone is having this same issue with Left.
https://itch.io/t/197211/change-theme-on-windows-7-not-working?before=3#post-365328

**Comment by neauoire** [comment]
But Left seems to already have this fix implemented.
https://github.com/hundredrabbits/Left/blob/master/desktop/sources/links/main.css#L4

**Comment by jakofranko** [comment]
I was looking at Left’s code yesterday and I think it’s the same issue, because I was seeing the same thing with Left on Windows 10. I believe I’ll have time to sit down tonight and make a fix for Left, yesterday got a little crazy.

**Comment by jakofranko** [comment]
Actually, just took a look at Left and it works fine, but you just have to make sure you drag the theme onto the main text area:

![2018-02-22 1](https://user-images.githubusercontent.com/3189302/36577264-748b87e0-1813-11e8-98cd-b00ff11db506.png)

vs

![2018-02-22](https://user-images.githubusercontent.com/3189302/36577265-75b9109c-1813-11e8-9d32-e6d0382349fd.png)

I can post on the itch.io post too to see if I can help :)

**Comment by jakofranko** [comment]
Woops, posted and then saw they had fixed it since I had looked at the issue earlier 🙈 glad they solved it!

**Comment by neauoire** [comment]
Ah! Excellent :) thank you!
